name: push_workflow_updates

on:
  push:
    branches:
      - main

jobs:
  push_workflow_updates:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: List Files
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=( $(curl -s -X GET -H -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '.[] | .filename') )

        for i in "${FILES[@]}"
        do
          request_body="{\"template_path\":\"$i\"}"
          webhook_signature_header="$(echo -n $request_body | openssl dgst -sha256 -hmac ${{ secrets.WEBHOOK_SECRET }} | awk '{print "x-webhook-signature: "$2}')"
          curl -X POST -H "${webhook_signature_header}" --data "${request_body}" https://3o5bijg2b0.execute-api.us-east-1.amazonaws.com/Prod/GithubAppUpdate/
        done